from __future__ import annotations

import hashlib
import json
import subprocess
import sys
import tempfile
import unittest
from dataclasses import replace
from pathlib import Path

from scripts.update_shared_test_status import HANDOFF, IDLE, LOCKED, StatusDocument
from scripts.verify_shared_test_release import (
    LAUNCHER_COMPONENT,
    PACKAGES,
    SERVER_PROBE_SCRIPT,
    VerificationConfig,
    VerificationError,
    build_parser,
    verify_and_transition,
)


LEASE_ID = "0123456789abcdef0123456789abcdef"
SERIAL = "P40PRO-ANEB-01"
HASHES = {
    "binary_sha256": "1" * 64,
    "qdisc_sha256": "2" * 64,
    "firewall_full_sha256": "3" * 64,
    "firewall_v4_sha256": "4" * 64,
    "firewall_v6_sha256": "5" * 64,
    "firewall_nft_sha256": "6" * 64,
}

HANDOFF_DOCUMENT = f"""# Codex / Claude 共享测试状态

## 当前状态

| 项目 | 内容 |
|---|---|
| 状态 | **待交接** |
| 当前执行者 | Codex |
| 当前任务 | M0-EC1 验证 |
| 占用资源 | P40 Pro、ANEB Codex、E-01 |
| 开始时间 | 2026-07-18 19:14 |
| 最近更新 | 2026-07-18 19:52 |
| 交接说明 | [ANEB_LEASE_ID:{LEASE_ID}] 清理完成，等待独立复核。 |

## 共同约定

保持原样。

## 最近记录

| 时间 | 执行者 | 任务 | 结果 |
|---|---|---|---|
| 2026-07-18 19:52 | Codex | M0-EC1 验证 | 清理完成；待独立复核 |
"""


def server_sample() -> dict[str, object]:
    return {
        "schema": "aneb-shared-release-server-probe-v1",
        "serverinfo_version": "aneb-server/0.7.0",
        "h3_enabled": True,
        "service_active": True,
        **HASHES,
        "wg_aneb_lab_present": False,
        "ifb_aneb_lab_present": False,
        "aneb_lab_present": False,
        "udp_51820_present": False,
    }


def extracted_canonicalizer():
    start = SERVER_PROBE_SCRIPT.index("def canonicalize_iptables_save(")
    end = SERVER_PROBE_SCRIPT.index("\n\ndef file_sha256", start)
    source = (
        "from datetime import datetime\n"
        "import re\n\n"
        + SERVER_PROBE_SCRIPT[start:end]
        + "\n"
    )
    namespace: dict[str, object] = {}
    exec(compile(source, "<extracted-server-canonicalizer>", "exec"), namespace)
    return namespace["canonicalize_iptables_save"]


def iptables_snapshot(
    timestamp: str,
    *,
    version: str = "v1.8.7",
    backend: str = "nf_tables",
    policy: str = "ACCEPT",
    port: int = 8443,
) -> bytes:
    return (
        f"# Generated by iptables-save {version} ({backend}) on {timestamp}\n"
        "*filter\n"
        f":INPUT {policy} [0:0]\n"
        f"-A INPUT -p tcp --dport {port} -j ACCEPT\n"
        "COMMIT\n"
        f"# Completed on {timestamp}\n"
    ).encode("ascii")


def set_status_state(path: Path, state: str) -> None:
    text = HANDOFF_DOCUMENT
    if state == IDLE:
        replacements = {
            "| 状态 | **待交接** |": "| 状态 | **空闲** |",
            "| 当前执行者 | Codex |": "| 当前执行者 | 无 |",
            "| 当前任务 | M0-EC1 验证 |": "| 当前任务 | 无 |",
            "| 占用资源 | P40 Pro、ANEB Codex、E-01 |": "| 占用资源 | 无 |",
            "| 开始时间 | 2026-07-18 19:14 |": "| 开始时间 | 无 |",
            f"| 交接说明 | [ANEB_LEASE_ID:{LEASE_ID}] 清理完成，等待独立复核。 |": (
                "| 交接说明 | 自动独立复核通过。 |"
            ),
        }
    elif state == LOCKED:
        replacements = {
            "| 状态 | **待交接** |": "| 状态 | **异常锁定** |",
            f"| 交接说明 | [ANEB_LEASE_ID:{LEASE_ID}] 清理完成，等待独立复核。 |": (
                f"| 交接说明 | [ANEB_LEASE_ID:{LEASE_ID}] 自动复核失败，已锁定。 |"
            ),
        }
    elif state == HANDOFF:
        replacements = {}
    else:
        raise AssertionError(state)
    for before, after in replacements.items():
        text = text.replace(before, after)
    path.write_bytes(text.replace("\n", "\r\n").encode("utf-8"))
    expected = state
    parsed = StatusDocument.parse(path.read_bytes()).snapshot.state
    if parsed != expected:
        raise AssertionError((parsed, expected))


class FakeRunner:
    def __init__(self, status: Path, samples: list[dict[str, object]] | None = None):
        self.status = status
        self.samples = list(samples or [server_sample(), server_sample()])
        self.calls: list[tuple[tuple[str, ...], str | None]] = []
        self.pid_package: str | None = None
        self.pid_package_round2: str | None = None
        self.service_package: str | None = None
        self.tun0 = False
        self.active_vpn_agent = False
        self.launcher_foreground = True
        self.stayon = "0"
        self.wifi_validated = True
        self.enabled_accessibility = "null"
        self.bound_accessibility = False
        self.shortcut_target_only = False
        self.transition_returncode = 0
        self.release_failures = 0
        self.p40_round = 0
        self.ssh_round = 0
        self.change_status_on_ssh_round: int | None = None

    def __call__(self, arguments, **kwargs):
        args = tuple(str(value) for value in arguments)
        input_text = kwargs.get("input")
        self.calls.append((args, input_text))
        if args[0] == "adb":
            return self._adb(args)
        if args[0] == "ssh":
            self.ssh_round += 1
            if self.change_status_on_ssh_round == self.ssh_round:
                self.status.write_bytes(
                    self.status.read_bytes() + b"<!-- changed during ssh probe -->\r\n"
                )
            if not self.samples:
                return subprocess.CompletedProcess(args, 1, "", "no sample")
            return subprocess.CompletedProcess(
                args,
                0,
                json.dumps(self.samples.pop(0), sort_keys=True),
                "",
            )
        if len(args) > 1 and Path(args[1]).name == "update_shared_test_status.py":
            return self._transition(args)
        return subprocess.CompletedProcess(args, 127, "", "unexpected command")

    def _adb(self, args: tuple[str, ...]):
        self.assert_exact_serial(args)
        command = args[3:]
        if command == ("get-serialno",):
            self.p40_round += 1
            return subprocess.CompletedProcess(args, 0, SERIAL + "\n", "")
        if command[:2] == ("shell", "pidof"):
            package = command[2]
            if package == self.pid_package or (
                self.p40_round == 2 and package == self.pid_package_round2
            ):
                return subprocess.CompletedProcess(args, 0, "8416\n", "")
            return subprocess.CompletedProcess(args, 1, "", "")
        if command[:4] == ("shell", "dumpsys", "activity", "services"):
            package = command[4]
            if package == self.service_package:
                output = f"ServiceRecord{{abcd u0 {package}/.CaptureService}}\n"
            else:
                output = "ACTIVITY MANAGER SERVICES\n  (nothing)\n"
            return subprocess.CompletedProcess(args, 0, output, "")
        if command == ("shell", "ip", "-o", "link", "show"):
            output = "1: lo: <LOOPBACK>\n2: wlan0: <UP>\n"
            if self.tun0:
                output += "39: tun0: <POINTOPOINT,UP>\n"
            return subprocess.CompletedProcess(args, 0, output, "")
        if command == (
            "shell",
            "settings",
            "get",
            "secure",
            "enabled_accessibility_services",
        ):
            return subprocess.CompletedProcess(
                args, 0, self.enabled_accessibility + "\n", ""
            )
        if command == ("shell", "dumpsys", "accessibility"):
            if self.bound_accessibility:
                output = (
                    "User state[\n  bound services:{"
                    "com.aneb.probe.codex/.AnEbAccessibilityService}\n]\n"
                )
            elif self.shortcut_target_only:
                output = (
                    "accessibility_shortcut_target_service="
                    "com.aneb.probe.codex/.AnEbAccessibilityService\n"
                    "bound services:{}\nEnabled services:{}\n"
                )
            else:
                output = "User state[\n  bound services:{}\n  Enabled services:{}\n]\n"
            return subprocess.CompletedProcess(args, 0, output, "")
        if command == ("shell", "dumpsys", "connectivity"):
            blocks = []
            if self.wifi_validated:
                blocks.append(
                    "NetworkAgentInfo{network{101} state=CONNECTED "
                    "nc{Transports: WIFI Capabilities: INTERNET&VALIDATED}}"
                )
            else:
                blocks.append(
                    "NetworkAgentInfo{network{101} state=CONNECTED "
                    "nc{Transports: WIFI Capabilities: INTERNET}}"
                )
            # Huawei emits this LISTEN request even when no VPN agent exists.
            blocks.append(
                "NetworkRequest [ LISTEN id=25, [ Transports: VPN "
                "Capabilities: NOT_RESTRICTED ] ]"
            )
            if self.active_vpn_agent:
                blocks.append(
                    "NetworkAgentInfo{network{202} state=CONNECTED "
                    "nc{Transports: VPN Capabilities: INTERNET&VALIDATED}}"
                )
            return subprocess.CompletedProcess(args, 0, "\n".join(blocks), "")
        if command == ("shell", "dumpsys", "activity", "activities"):
            component = (
                LAUNCHER_COMPONENT
                if self.launcher_foreground
                else "com.example.business/.MainActivity"
            )
            output = f"mResumedActivity: ActivityRecord{{abcd u0 {component} t10}}\n"
            return subprocess.CompletedProcess(args, 0, output, "")
        if command == (
            "shell",
            "settings",
            "get",
            "global",
            "stay_on_while_plugged_in",
        ):
            return subprocess.CompletedProcess(args, 0, self.stayon + "\n", "")
        return subprocess.CompletedProcess(args, 127, "", "unexpected adb probe")

    @staticmethod
    def assert_exact_serial(args: tuple[str, ...]) -> None:
        if args[:3] != ("adb", "-s", SERIAL):
            raise AssertionError(args)

    def _transition(self, args: tuple[str, ...]):
        if self.transition_returncode:
            return subprocess.CompletedProcess(args, self.transition_returncode, "", "failed")
        if "review-release" in args and self.release_failures:
            self.release_failures -= 1
            return subprocess.CompletedProcess(args, 2, "", "release failed")
        sha_index = args.index("--expected-status-sha256") + 1
        expected = args[sha_index]
        actual = hashlib.sha256(self.status.read_bytes()).hexdigest()
        if expected != actual:
            return subprocess.CompletedProcess(args, 2, "", "sha mismatch")
        if "review-release" in args:
            set_status_state(self.status, IDLE)
        elif "review-lock" in args:
            set_status_state(self.status, LOCKED)
        else:
            return subprocess.CompletedProcess(args, 2, "", "unknown transition")
        return subprocess.CompletedProcess(args, 0, "OK\n", "")

    def transition_calls(self) -> list[tuple[str, ...]]:
        return [
            args
            for args, _ in self.calls
            if len(args) > 1 and Path(args[1]).name == "update_shared_test_status.py"
        ]


class SharedReleaseVerifierTest(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)
        self.status = self.root / "SHARED_TEST_STATUS.md"
        self.key = self.root / "e01.key"
        self.updater = self.root / "update_shared_test_status.py"
        set_status_state(self.status, HANDOFF)
        self.key.write_text("test key placeholder", encoding="utf-8")
        self.updater.write_text("# intercepted by FakeRunner\n", encoding="utf-8")
        self.config = VerificationConfig(
            status_file=self.status,
            status_updater=self.updater,
            adb_path="adb",
            adb_serial=SERIAL,
            ssh_path="ssh",
            ssh_host="root@120.79.148.0",
            ssh_key=self.key,
            ssh_port=22,
            expected_version="aneb-server/0.7.0",
            expected_binary_sha256=HASHES["binary_sha256"],
            expected_qdisc_sha256=HASHES["qdisc_sha256"],
            expected_firewall_full_sha256=HASHES["firewall_full_sha256"],
            expected_firewall_v4_sha256=HASHES["firewall_v4_sha256"],
            expected_firewall_v6_sha256=HASHES["firewall_v6_sha256"],
            expected_firewall_nft_sha256=HASHES["firewall_nft_sha256"],
            interval_seconds=10,
        )

    def tearDown(self) -> None:
        self.temp.cleanup()

    def test_two_clean_rounds_release_with_original_status_sha(self) -> None:
        runner = FakeRunner(self.status)
        original_sha = hashlib.sha256(self.status.read_bytes()).hexdigest()
        sleeps: list[float] = []

        outcome = verify_and_transition(
            self.config,
            run_command=runner,
            sleep=sleeps.append,
        )

        self.assertTrue(outcome.success)
        self.assertEqual("released", outcome.transition)
        self.assertEqual(original_sha, outcome.original_status_sha256)
        self.assertEqual([10.0], sleeps)
        self.assertEqual(IDLE, StatusDocument.parse(self.status.read_bytes()).snapshot.state)
        ssh_calls = [(args, payload) for args, payload in runner.calls if args[0] == "ssh"]
        self.assertEqual(2, len(ssh_calls))
        self.assertTrue(all(payload == SERVER_PROBE_SCRIPT for _, payload in ssh_calls))
        adb_calls = [args for args, _ in runner.calls if args[0] == "adb"]
        self.assertEqual(2, sum(args[3:] == ("get-serialno",) for args in adb_calls))
        self.assertTrue(all(args[:3] == ("adb", "-s", SERIAL) for args in adb_calls))
        transition = runner.transition_calls()
        self.assertEqual(1, len(transition))
        self.assertIn("review-release", transition[0])
        self.assertNotIn("review-lock", transition[0])
        self.assertEqual("Verifier", transition[0][transition[0].index("--executor") + 1])
        self.assertEqual(
            original_sha,
            transition[0][transition[0].index("--expected-status-sha256") + 1],
        )
        evidence = transition[0][transition[0].index("--evidence") + 1]
        self.assertIn("T+0/T+10", evidence)

    def test_huawei_listen_vpn_is_ignored_but_vpn_agent_locks(self) -> None:
        runner = FakeRunner(self.status)
        runner.active_vpn_agent = True

        outcome = verify_and_transition(
            replace(self.config, interval_seconds=15),
            run_command=runner,
            sleep=lambda _: None,
        )

        self.assertFalse(outcome.success)
        self.assertEqual("p40_vpn_network_agent_active", outcome.code)
        self.assertEqual("locked", outcome.transition)
        self.assertEqual(LOCKED, StatusDocument.parse(self.status.read_bytes()).snapshot.state)
        transition = runner.transition_calls()[0]
        self.assertIn("review-lock", transition)
        self.assertEqual(
            outcome.original_status_sha256,
            transition[transition.index("--expected-status-sha256") + 1],
        )
        evidence = transition[transition.index("--evidence") + 1]
        self.assertIn("T+0/T+15", evidence)

    def test_release_command_failure_locks_the_unchanged_handoff(self) -> None:
        runner = FakeRunner(self.status)
        runner.release_failures = 1

        outcome = verify_and_transition(self.config, run_command=runner, sleep=lambda _: None)

        self.assertFalse(outcome.success)
        self.assertEqual("status_review_release_failed", outcome.code)
        self.assertEqual("locked", outcome.transition)
        transitions = runner.transition_calls()
        self.assertEqual(2, len(transitions))
        self.assertIn("review-release", transitions[0])
        self.assertIn("review-lock", transitions[1])
        self.assertEqual(LOCKED, StatusDocument.parse(self.status.read_bytes()).snapshot.state)

    def test_each_package_pid_and_service_record_is_checked(self) -> None:
        for package in PACKAGES:
            for failure_kind in ("pid", "service"):
                with self.subTest(package=package, failure=failure_kind):
                    set_status_state(self.status, HANDOFF)
                    runner = FakeRunner(self.status)
                    if failure_kind == "pid":
                        runner.pid_package = package
                        expected = "p40_package_pid_active"
                    else:
                        runner.service_package = package
                        expected = "p40_service_record_active"
                    outcome = verify_and_transition(
                        self.config,
                        run_command=runner,
                        sleep=lambda _: None,
                    )
                    self.assertEqual(expected, outcome.code)
                    self.assertEqual("locked", outcome.transition)

    def test_other_p40_release_failures_lock(self) -> None:
        mutations = {
            "tun0": ("tun0", True, "p40_tun0_active"),
            "launcher": ("launcher_foreground", False, "p40_launcher_not_foreground"),
            "stayon": ("stayon", "3", "p40_stayon_enabled"),
            "wifi": ("wifi_validated", False, "p40_validated_wifi_missing"),
        }
        for name, (attribute, value, expected) in mutations.items():
            with self.subTest(name=name):
                set_status_state(self.status, HANDOFF)
                runner = FakeRunner(self.status)
                setattr(runner, attribute, value)
                outcome = verify_and_transition(
                    self.config,
                    run_command=runner,
                    sleep=lambda _: None,
                )
                self.assertEqual(expected, outcome.code)
                self.assertEqual("locked", outcome.transition)

    def test_aneb_accessibility_enabled_or_bound_locks_but_shortcut_only_is_allowed(self) -> None:
        cases = (
            (
                "enabled",
                "enabled_accessibility",
                "com.example.reader/.Reader:com.aneb.probe/.AnEbAccessibilityService",
                "p40_aneb_accessibility_enabled",
            ),
            (
                "bound",
                "bound_accessibility",
                True,
                "p40_aneb_accessibility_bound",
            ),
        )
        for name, attribute, value, expected in cases:
            with self.subTest(name=name):
                set_status_state(self.status, HANDOFF)
                runner = FakeRunner(self.status)
                setattr(runner, attribute, value)
                outcome = verify_and_transition(
                    self.config,
                    run_command=runner,
                    sleep=lambda _: None,
                )
                self.assertEqual(expected, outcome.code)
                self.assertEqual("locked", outcome.transition)

        set_status_state(self.status, HANDOFF)
        shortcut_runner = FakeRunner(self.status)
        shortcut_runner.shortcut_target_only = True
        outcome = verify_and_transition(
            self.config,
            run_command=shortcut_runner,
            sleep=lambda _: None,
        )
        self.assertTrue(outcome.success)
        adb_commands = [args[3:] for args, _ in shortcut_runner.calls if args[0] == "adb"]
        self.assertIn(
            (
                "shell",
                "settings",
                "get",
                "secure",
                "enabled_accessibility_services",
            ),
            adb_commands,
        )
        self.assertIn(("shell", "dumpsys", "accessibility"), adb_commands)

    def test_e01_identity_hash_and_phase0_failures_lock(self) -> None:
        mutations: list[tuple[str, object, str]] = [
            ("serverinfo_version", "aneb-server/0.8.0", "e01_version_mismatch"),
            ("h3_enabled", False, "e01_h3_disabled"),
            ("service_active", False, "e01_service_inactive"),
            ("wg_aneb_lab_present", True, "e01_phase0_residue_present"),
            ("ifb_aneb_lab_present", True, "e01_phase0_residue_present"),
            ("aneb_lab_present", True, "e01_phase0_residue_present"),
            ("udp_51820_present", True, "e01_phase0_residue_present"),
        ]
        for key in HASHES:
            mutations.append((key, "f" * 64, f"e01_{key}_mismatch"))
        for key, value, expected in mutations:
            with self.subTest(key=key):
                set_status_state(self.status, HANDOFF)
                changed = server_sample()
                changed[key] = value
                runner = FakeRunner(self.status, [changed])
                outcome = verify_and_transition(
                    self.config,
                    run_command=runner,
                    sleep=lambda _: None,
                )
                self.assertEqual(expected, outcome.code)
                self.assertEqual("locked", outcome.transition)

    def test_status_change_between_rounds_never_calls_release_or_lock(self) -> None:
        runner = FakeRunner(self.status)

        def concurrent_change(_: float) -> None:
            self.status.write_bytes(self.status.read_bytes() + b"<!-- concurrent -->\r\n")

        outcome = verify_and_transition(
            self.config,
            run_command=runner,
            sleep=concurrent_change,
        )

        self.assertFalse(outcome.success)
        self.assertEqual("status_changed_during_review", outcome.code)
        self.assertEqual("none", outcome.transition)
        self.assertEqual([], runner.transition_calls())
        self.assertTrue(self.status.read_bytes().endswith(b"<!-- concurrent -->\r\n"))

    def test_second_round_p40_failure_locks_instead_of_releasing(self) -> None:
        runner = FakeRunner(self.status)
        runner.pid_package_round2 = "com.aneb.probe.codex"

        outcome = verify_and_transition(
            self.config,
            run_command=runner,
            sleep=lambda _: None,
        )

        self.assertEqual("p40_package_pid_active", outcome.code)
        self.assertEqual("locked", outcome.transition)
        self.assertEqual(1, runner.ssh_round)
        transitions = runner.transition_calls()
        self.assertEqual(1, len(transitions))
        self.assertIn("review-lock", transitions[0])

    def test_second_round_e01_failure_locks_instead_of_releasing(self) -> None:
        second = server_sample()
        second["udp_51820_present"] = True
        runner = FakeRunner(self.status, [server_sample(), second])

        outcome = verify_and_transition(
            self.config,
            run_command=runner,
            sleep=lambda _: None,
        )

        self.assertEqual("e01_phase0_residue_present", outcome.code)
        self.assertEqual("locked", outcome.transition)
        self.assertEqual(2, runner.ssh_round)
        transitions = runner.transition_calls()
        self.assertEqual(1, len(transitions))
        self.assertIn("review-lock", transitions[0])

    def test_status_change_during_second_server_probe_is_never_overwritten(self) -> None:
        runner = FakeRunner(self.status)
        runner.change_status_on_ssh_round = 2

        outcome = verify_and_transition(
            self.config,
            run_command=runner,
            sleep=lambda _: None,
        )

        self.assertEqual("status_changed_during_review", outcome.code)
        self.assertEqual("none", outcome.transition)
        self.assertEqual([], runner.transition_calls())
        self.assertTrue(
            self.status.read_bytes().endswith(b"<!-- changed during ssh probe -->\r\n")
        )

    def test_status_must_start_as_handoff(self) -> None:
        set_status_state(self.status, IDLE)
        runner = FakeRunner(self.status)
        with self.assertRaisesRegex(VerificationError, "status_not_handoff"):
            verify_and_transition(
                self.config,
                run_command=runner,
                sleep=lambda _: None,
            )
        self.assertEqual([], runner.calls)

    def test_parser_accepts_required_identity_and_hash_aliases(self) -> None:
        args = build_parser().parse_args(
            [
                "--status-file", str(self.status),
                "--status-updater", str(self.updater),
                "--serial", SERIAL,
                "--ssh-host", "root@120.79.148.0",
                "--ssh-key", str(self.key),
                "--interval-seconds", "15",
                "--command-timeout-seconds", "15",
                "--expected-version", "aneb-server/0.7.0",
                "--expected-binary-sha256", HASHES["binary_sha256"],
                "--expected-qdisc-sha256", HASHES["qdisc_sha256"],
                "--expected-firewall-sha256", HASHES["firewall_full_sha256"],
                "--expected-iptables-v4-sha256", HASHES["firewall_v4_sha256"],
                "--expected-iptables-v6-sha256", HASHES["firewall_v6_sha256"],
                "--expected-nft-sha256", HASHES["firewall_nft_sha256"],
            ]
        )
        self.assertEqual(SERIAL, args.adb_serial)
        self.assertEqual(HASHES["firewall_full_sha256"], args.expected_firewall_full_sha256)
        self.assertEqual(15.0, args.interval_seconds)
        self.assertEqual(15.0, args.command_timeout_seconds)
        defaults = build_parser().parse_args(
            [
                "--serial", SERIAL,
                "--ssh-host", "root@120.79.148.0",
                "--ssh-key", str(self.key),
                "--expected-version", "aneb-server/0.7.0",
                "--expected-binary-sha256", HASHES["binary_sha256"],
                "--expected-qdisc-sha256", HASHES["qdisc_sha256"],
                "--expected-firewall-sha256", HASHES["firewall_full_sha256"],
                "--expected-iptables-v4-sha256", HASHES["firewall_v4_sha256"],
                "--expected-iptables-v6-sha256", HASHES["firewall_v6_sha256"],
                "--expected-nft-sha256", HASHES["firewall_nft_sha256"],
            ]
        )
        self.assertEqual(10.0, defaults.interval_seconds)
        self.assertEqual(30.0, defaults.command_timeout_seconds)

    def test_interval_outside_ten_to_three_hundred_seconds_is_rejected(self) -> None:
        for interval in (0, 9.99, 301):
            with self.subTest(interval=interval):
                runner = FakeRunner(self.status)
                with self.assertRaisesRegex(VerificationError, "interval_invalid"):
                    verify_and_transition(
                        replace(self.config, interval_seconds=interval),
                        run_command=runner,
                        sleep=lambda _: None,
                    )
                self.assertEqual([], runner.calls)

    def test_extracted_server_canonicalizer_ignores_only_valid_run_times(self) -> None:
        canonicalize = extracted_canonicalizer()
        first_raw = iptables_snapshot("Sat Jul 18 19:00:00 2026")
        second_raw = iptables_snapshot("Sat Jul 18 19:00:02 2026")
        first = canonicalize(first_raw, "iptables-save")
        second = canonicalize(second_raw, "iptables-save")
        self.assertEqual(first, second)
        self.assertEqual(hashlib.sha256(first).digest(), hashlib.sha256(second).digest())
        self.assertIn(b"iptables-save v1.8.7 (nf_tables)", first)
        self.assertNotIn(b"19:00:00", first)
        self.assertNotIn(b"# Completed on", first)

        semantic_changes = {
            "rule": iptables_snapshot("Sat Jul 18 19:00:02 2026", port=8444),
            "policy": iptables_snapshot(
                "Sat Jul 18 19:00:02 2026", policy="DROP"
            ),
            "tool-version": iptables_snapshot(
                "Sat Jul 18 19:00:02 2026", version="v1.8.8"
            ),
            "tool-backend": iptables_snapshot(
                "Sat Jul 18 19:00:02 2026", backend="legacy"
            ),
        }
        for name, changed_raw in semantic_changes.items():
            with self.subTest(name=name):
                changed = canonicalize(changed_raw, "iptables-save")
                self.assertNotEqual(first, changed)
                self.assertNotEqual(
                    hashlib.sha256(first).digest(),
                    hashlib.sha256(changed).digest(),
                )

        malformed = {
            "missing-header": b"*filter\nCOMMIT\n# Completed on Sat Jul 18 19:00:00 2026\n",
            "missing-footer": first_raw.rsplit(b"# Completed on", 1)[0],
            "duplicated-wrapper": first_raw + first_raw,
            "malformed-time": first_raw.replace(
                b"Sat Jul 18 19:00:00 2026", b"2026-07-18T19:00:00", 1
            ),
        }
        for name, payload in malformed.items():
            with self.subTest(name=name):
                with self.assertRaises(SystemExit):
                    canonicalize(payload, "iptables-save")
        with self.assertRaises(SystemExit):
            canonicalize(first_raw, "ip6tables-save")

    def test_probe_commands_are_read_only_and_remote_snapshot_is_strict(self) -> None:
        runner = FakeRunner(self.status)
        verify_and_transition(self.config, run_command=runner, sleep=lambda _: None)
        probe_calls = [
            args
            for args, _ in runner.calls
            if args[0] in {"adb", "ssh"}
        ]
        rendered = "\n".join(" ".join(args) for args in probe_calls).casefold()
        for forbidden in (
            "force-stop",
            " settings put ",
            " settings delete ",
            " pm clear ",
            " am start ",
            " svc ",
        ):
            self.assertNotIn(forbidden, rendered)
        for required in (
            'run(["iptables-save"])',
            'run(["ip6tables-save"])',
            'run(["nft", "--stateless", "list", "ruleset"])',
            'run(["systemctl", "is-active", "aneb-server"])',
            'run(["tc", "qdisc", "show", "dev", "eth0"])',
            'run(["ss", "-H", "-lun", "sport", "=", ":51820"])',
        ):
            self.assertIn(required, SERVER_PROBE_SCRIPT)
        for forbidden in (
            "iptables -",
            "ip6tables -",
            "nft add",
            "nft delete",
            "systemctl restart",
            "systemctl stop",
            "systemctl start",
            "tc qdisc add",
            "tc qdisc del",
            "ip link add",
            "ip link del",
        ):
            self.assertNotIn(forbidden, SERVER_PROBE_SCRIPT.casefold())


if __name__ == "__main__":
    unittest.main()
