#!/usr/bin/env python3
"""Independently verify a shared ANEB handoff before releasing it.

The verifier performs two read-only P40/E-01 snapshots.  The only mutation it
can request is an expected-hash-guarded transition through
``update_shared_test_status.py`` after the probes have finished.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import time
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Callable, Mapping, Sequence, TextIO

if __package__:
    from .update_shared_test_status import (
        HANDOFF,
        IDLE,
        LOCKED,
        StatusDocument,
        StatusError,
        default_status_file,
    )
else:  # Direct ``python scripts/verify_shared_test_release.py`` execution.
    from update_shared_test_status import (  # type: ignore[no-redef]
        HANDOFF,
        IDLE,
        LOCKED,
        StatusDocument,
        StatusError,
        default_status_file,
    )


REVIEWER = "Verifier"
PACKAGES = (
    "com.aneb.probe.codex",
    "com.aneb.probe",
    "com.emanuelef.remote_capture",
    "com.pcapdroid.mitm",
    "com.wireguard.android",
)
ANEB_PACKAGES = ("com.aneb.probe.codex", "com.aneb.probe")
LAUNCHER_COMPONENT = "com.huawei.android.launcher/.unihome.UniHomeLauncher"
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
SERIAL_RE = re.compile(r"^[A-Za-z0-9._:-]+$")
SSH_HOST_RE = re.compile(r"^[A-Za-z0-9._@:\[\]-]+$")
VERSION_RE = re.compile(r"^[A-Za-z0-9._/-]+$")
SERVICE_RECORD_RE = re.compile(r"\bServiceRecord\{")
TUN0_RE = re.compile(r"(?m)^\d+:\s+tun0(?:@[^:]+)?:")
RESUMED_RE = re.compile(r"(?:mResumedActivity|topResumedActivity|ResumedActivity)")
SHORTCUT_TARGET_ONLY_RE = re.compile(
    r"^accessibility_shortcut_target_service\s*=\s*"
    r"[a-z0-9._]+/[a-z0-9.$_]+$",
    flags=re.IGNORECASE,
)


SERVER_PROBE_SCRIPT = r'''from __future__ import annotations

from datetime import datetime
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess

os.environ["LC_ALL"] = "C"


def run(arguments, allowed=(0,)):
    completed = subprocess.run(
        arguments,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode not in allowed:
        raise SystemExit("read-only probe command failed")
    return completed


def canonicalize_iptables_save(data, expected_tool):
    if not data:
        raise SystemExit("empty iptables-save snapshot")
    lines = data.splitlines(keepends=True)
    if len(lines) < 2:
        raise SystemExit("incomplete iptables-save snapshot")
    bodies = [line.rstrip(b"\r\n") for line in lines]
    generated = [
        index for index, body in enumerate(bodies)
        if body.startswith(b"# Generated by")
    ]
    completed = [
        index for index, body in enumerate(bodies)
        if body.startswith(b"# Completed on")
    ]
    if generated != [0] or completed != [len(lines) - 1]:
        raise SystemExit("iptables-save wrapper positions invalid")

    expected = expected_tool.encode("ascii")
    header = bodies[0]
    header_prefix = b"# Generated by " + expected + b" "
    if not header.startswith(header_prefix):
        raise SystemExit("iptables-save tool identity mismatch")
    identity, separator, generated_timestamp = header.rpartition(b" on ")
    if (
        not separator
        or not identity.startswith(header_prefix)
        or not identity[len(header_prefix):].strip()
    ):
        raise SystemExit("malformed iptables-save header")
    completed_prefix = b"# Completed on "
    if not bodies[-1].startswith(completed_prefix):
        raise SystemExit("malformed iptables-save footer")
    completed_timestamp = bodies[-1][len(completed_prefix):]

    timestamp_pattern = re.compile(
        rb"(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun) "
        rb"(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) "
        rb"(?: [1-9]|[12][0-9]|3[01]) "
        rb"(?:[01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9] [0-9]{4}"
    )

    def validate_timestamp(value):
        if timestamp_pattern.fullmatch(value) is None:
            raise SystemExit("malformed iptables-save timestamp")
        try:
            text = value.decode("ascii")
            parsed = datetime.strptime(text, "%a %b %d %H:%M:%S %Y")
        except (UnicodeDecodeError, ValueError) as error:
            raise SystemExit("invalid iptables-save timestamp") from error
        canonical = "{} {:2d} {}".format(
            parsed.strftime("%a %b"),
            parsed.day,
            parsed.strftime("%H:%M:%S %Y"),
        )
        if text != canonical:
            raise SystemExit("non-canonical iptables-save timestamp")

    validate_timestamp(generated_timestamp)
    validate_timestamp(completed_timestamp)
    newline = (
        b"\r\n" if lines[0].endswith(b"\r\n")
        else b"\n" if lines[0].endswith(b"\n")
        else b""
    )
    if not newline:
        raise SystemExit("iptables-save header lacks newline")
    return identity + newline + b"".join(lines[1:-1])


def file_sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


v4 = canonicalize_iptables_save(run(["iptables-save"]).stdout, "iptables-save")
v6 = canonicalize_iptables_save(run(["ip6tables-save"]).stdout, "ip6tables-save")
if shutil.which("nft"):
    nft = run(["nft", "--stateless", "list", "ruleset"]).stdout
else:
    nft = b"nft=absent\n"

v4_marker = b"--- iptables-save ---\n"
v6_marker = b"--- ip6tables-save ---\n"
nft_marker = b"--- nft-list-ruleset ---\n"
firewall = v4_marker + v4 + v6_marker + v6 + nft_marker + nft

serverinfo_raw = run([
    "curl", "--silent", "--show-error", "--fail",
    "--connect-timeout", "5", "--max-time", "10",
    "--cacert", "/opt/aneb/tls/ip/cert.pem",
    "--resolve", "120.79.148.0:8443:127.0.0.1",
    "https://120.79.148.0:8443/api/v1/serverinfo",
]).stdout
try:
    serverinfo = json.loads(serverinfo_raw)
except (UnicodeDecodeError, json.JSONDecodeError) as error:
    raise SystemExit("serverinfo is not JSON") from error
if not isinstance(serverinfo, dict):
    raise SystemExit("serverinfo root is not an object")

service_active = run(["systemctl", "is-active", "aneb-server"]).stdout == b"active\n"
qdisc = run(["tc", "qdisc", "show", "dev", "eth0"]).stdout


def link_present(name):
    completed = run(["ip", "-o", "link", "show", "dev", name], allowed=(0, 1))
    return completed.returncode == 0


udp_51820 = run(["ss", "-H", "-lun", "sport", "=", ":51820"]).stdout
aneb_lab_present = b"ANEB_LAB" in v4 or b"ANEB_LAB" in v6 or b"ANEB_LAB" in nft
digest = lambda value: hashlib.sha256(value).hexdigest()
result = {
    "schema": "aneb-shared-release-server-probe-v1",
    "serverinfo_version": serverinfo.get("version"),
    "h3_enabled": serverinfo.get("h3_enabled"),
    "service_active": service_active,
    "binary_sha256": file_sha256("/opt/aneb/bin/aneb-server"),
    "qdisc_sha256": digest(qdisc),
    "firewall_full_sha256": digest(firewall),
    "firewall_v4_sha256": digest(v4),
    "firewall_v6_sha256": digest(v6),
    "firewall_nft_sha256": digest(nft),
    "wg_aneb_lab_present": link_present("wg-aneb-lab"),
    "ifb_aneb_lab_present": link_present("ifb-aneb-lab"),
    "aneb_lab_present": aneb_lab_present,
    "udp_51820_present": bool(udp_51820.strip()),
}
print(json.dumps(result, sort_keys=True, separators=(",", ":")))
'''


class VerificationError(Exception):
    """A bounded, non-sensitive verification failure."""

    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


RunCommand = Callable[..., subprocess.CompletedProcess[str]]
Sleep = Callable[[float], None]


@dataclass(frozen=True)
class VerificationConfig:
    status_file: Path
    status_updater: Path
    adb_path: str
    adb_serial: str
    ssh_path: str
    ssh_host: str
    ssh_key: Path
    ssh_port: int
    expected_version: str
    expected_binary_sha256: str
    expected_qdisc_sha256: str
    expected_firewall_full_sha256: str
    expected_firewall_v4_sha256: str
    expected_firewall_v6_sha256: str
    expected_firewall_nft_sha256: str
    interval_seconds: float = 10.0
    command_timeout_seconds: float = 30.0


@dataclass(frozen=True)
class VerificationOutcome:
    success: bool
    code: str
    transition: str
    original_status_sha256: str


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _validate_config(config: VerificationConfig) -> VerificationConfig:
    if SERIAL_RE.fullmatch(config.adb_serial) is None:
        raise VerificationError("adb_serial_invalid")
    if (
        SSH_HOST_RE.fullmatch(config.ssh_host) is None
        or config.ssh_host.startswith("-")
    ):
        raise VerificationError("ssh_host_invalid")
    if VERSION_RE.fullmatch(config.expected_version) is None:
        raise VerificationError("expected_version_invalid")
    if not 1 <= config.ssh_port <= 65535:
        raise VerificationError("ssh_port_invalid")
    try:
        interval_seconds = float(config.interval_seconds)
    except (TypeError, ValueError) as error:
        raise VerificationError("interval_invalid") from error
    if not 10 <= interval_seconds <= 300:
        raise VerificationError("interval_invalid")
    if not 1 <= config.command_timeout_seconds <= 300:
        raise VerificationError("command_timeout_invalid")
    for value in (
        config.expected_binary_sha256,
        config.expected_qdisc_sha256,
        config.expected_firewall_full_sha256,
        config.expected_firewall_v4_sha256,
        config.expected_firewall_v6_sha256,
        config.expected_firewall_nft_sha256,
    ):
        if SHA256_RE.fullmatch(value.lower()) is None:
            raise VerificationError("expected_sha256_invalid")
    if config.status_file.is_symlink() or not config.status_file.is_file():
        raise VerificationError("status_file_invalid")
    if config.status_updater.is_symlink() or not config.status_updater.is_file():
        raise VerificationError("status_updater_invalid")
    if config.ssh_key.is_symlink() or not config.ssh_key.is_file():
        raise VerificationError("ssh_key_invalid")
    return replace(
        config,
        expected_binary_sha256=config.expected_binary_sha256.lower(),
        expected_qdisc_sha256=config.expected_qdisc_sha256.lower(),
        expected_firewall_full_sha256=config.expected_firewall_full_sha256.lower(),
        expected_firewall_v4_sha256=config.expected_firewall_v4_sha256.lower(),
        expected_firewall_v6_sha256=config.expected_firewall_v6_sha256.lower(),
        expected_firewall_nft_sha256=config.expected_firewall_nft_sha256.lower(),
        interval_seconds=interval_seconds,
    )


def _run(
    run_command: RunCommand,
    arguments: Sequence[str],
    *,
    timeout: float,
    input_text: str | None = None,
    allowed_returncodes: tuple[int, ...] = (0,),
    failure_code: str = "external_command_failed",
) -> subprocess.CompletedProcess[str]:
    try:
        completed = run_command(
            list(arguments),
            input=input_text,
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as error:
        raise VerificationError(failure_code) from error
    if completed.returncode not in allowed_returncodes:
        raise VerificationError(failure_code)
    if not isinstance(completed.stdout, str) or not isinstance(completed.stderr, str):
        raise VerificationError(failure_code)
    return completed


def _adb(
    config: VerificationConfig,
    run_command: RunCommand,
    *arguments: str,
    allowed_returncodes: tuple[int, ...] = (0,),
) -> subprocess.CompletedProcess[str]:
    return _run(
        run_command,
        [config.adb_path, "-s", config.adb_serial, *arguments],
        timeout=config.command_timeout_seconds,
        allowed_returncodes=allowed_returncodes,
        failure_code="adb_probe_failed",
    )


def _network_agent_blocks(payload: str) -> tuple[str, ...]:
    markers = list(re.finditer(r"\bNetwork(?:AgentInfo|Request)\b", payload))
    blocks: list[str] = []
    for index, marker in enumerate(markers):
        if marker.group(0) != "NetworkAgentInfo":
            continue
        end = markers[index + 1].start() if index + 1 < len(markers) else len(payload)
        blocks.append(payload[marker.start():end])
    return tuple(blocks)


def _has_transport(block: str, transport: str) -> bool:
    return re.search(
        rf"\bTransports\s*:\s*[^\]\r\n}}]*\b{re.escape(transport)}\b",
        block,
        flags=re.IGNORECASE,
    ) is not None


def _probe_p40(config: VerificationConfig, run_command: RunCommand) -> None:
    serial = _adb(config, run_command, "get-serialno").stdout.strip()
    if serial != config.adb_serial:
        raise VerificationError("adb_serial_mismatch")

    for package in PACKAGES:
        pid = _adb(
            config,
            run_command,
            "shell",
            "pidof",
            package,
            allowed_returncodes=(0, 1),
        )
        if pid.returncode != 1 or pid.stdout.strip():
            raise VerificationError("p40_package_pid_active")
        services = _adb(
            config,
            run_command,
            "shell",
            "dumpsys",
            "activity",
            "services",
            package,
        ).stdout
        if SERVICE_RECORD_RE.search(services):
            raise VerificationError("p40_service_record_active")

    enabled_accessibility = _adb(
        config,
        run_command,
        "shell",
        "settings",
        "get",
        "secure",
        "enabled_accessibility_services",
    ).stdout.strip()
    enabled_components = {
        component.strip()
        for component in enabled_accessibility.split(":")
        if component.strip() and component.strip().casefold() != "null"
    }
    if any(
        component == package or component.startswith(package + "/")
        for component in enabled_components
        for package in ANEB_PACKAGES
    ):
        raise VerificationError("p40_aneb_accessibility_enabled")

    accessibility_dump = _adb(
        config, run_command, "shell", "dumpsys", "accessibility"
    ).stdout
    for line in accessibility_dump.splitlines():
        # A configured shortcut target is inert and is deliberately preserved.
        if SHORTCUT_TARGET_ONLY_RE.fullmatch(line.strip()):
            continue
        if any(package in line for package in ANEB_PACKAGES):
            raise VerificationError("p40_aneb_accessibility_bound")

    links = _adb(config, run_command, "shell", "ip", "-o", "link", "show").stdout
    if TUN0_RE.search(links):
        raise VerificationError("p40_tun0_active")

    connectivity = _adb(
        config, run_command, "shell", "dumpsys", "connectivity"
    ).stdout
    agents = _network_agent_blocks(connectivity)
    if any(_has_transport(block, "VPN") for block in agents):
        raise VerificationError("p40_vpn_network_agent_active")
    wifi_agents = [block for block in agents if _has_transport(block, "WIFI")]
    if not any(
        re.search(r"\bCONNECTED\b", block, flags=re.IGNORECASE)
        and re.search(r"\bVALIDATED\b", block, flags=re.IGNORECASE)
        for block in wifi_agents
    ):
        raise VerificationError("p40_validated_wifi_missing")

    activities = _adb(
        config, run_command, "shell", "dumpsys", "activity", "activities"
    ).stdout
    resumed = [line for line in activities.splitlines() if RESUMED_RE.search(line)]
    if not resumed or not any(LAUNCHER_COMPONENT in line for line in resumed):
        raise VerificationError("p40_launcher_not_foreground")

    stayon = _adb(
        config,
        run_command,
        "shell",
        "settings",
        "get",
        "global",
        "stay_on_while_plugged_in",
    ).stdout.strip().casefold()
    if stayon not in {"0", "false"}:
        raise VerificationError("p40_stayon_enabled")


SERVER_KEYS = frozenset(
    {
        "schema",
        "serverinfo_version",
        "h3_enabled",
        "service_active",
        "binary_sha256",
        "qdisc_sha256",
        "firewall_full_sha256",
        "firewall_v4_sha256",
        "firewall_v6_sha256",
        "firewall_nft_sha256",
        "wg_aneb_lab_present",
        "ifb_aneb_lab_present",
        "aneb_lab_present",
        "udp_51820_present",
    }
)
SERVER_HASH_KEYS = (
    "binary_sha256",
    "qdisc_sha256",
    "firewall_full_sha256",
    "firewall_v4_sha256",
    "firewall_v6_sha256",
    "firewall_nft_sha256",
)


def _probe_server(
    config: VerificationConfig, run_command: RunCommand
) -> Mapping[str, object]:
    command = [
        config.ssh_path,
        "-T",
        "-p",
        str(config.ssh_port),
        "-i",
        str(config.ssh_key),
        "-o",
        "BatchMode=yes",
        "-o",
        "StrictHostKeyChecking=yes",
        "-o",
        "UpdateHostKeys=no",
        "-o",
        "ConnectTimeout=10",
        config.ssh_host,
        "python3",
        "-",
    ]
    completed = _run(
        run_command,
        command,
        input_text=SERVER_PROBE_SCRIPT,
        timeout=config.command_timeout_seconds,
        failure_code="e01_probe_failed",
    )
    if completed.stderr.strip():
        raise VerificationError("e01_probe_stderr")
    try:
        payload = json.loads(completed.stdout)
    except json.JSONDecodeError as error:
        raise VerificationError("e01_probe_json_invalid") from error
    if not isinstance(payload, dict) or set(payload) != SERVER_KEYS:
        raise VerificationError("e01_probe_schema_invalid")
    if payload["schema"] != "aneb-shared-release-server-probe-v1":
        raise VerificationError("e01_probe_schema_invalid")
    if payload["serverinfo_version"] != config.expected_version:
        raise VerificationError("e01_version_mismatch")
    if payload["h3_enabled"] is not True:
        raise VerificationError("e01_h3_disabled")
    if payload["service_active"] is not True:
        raise VerificationError("e01_service_inactive")

    expected = {
        "binary_sha256": config.expected_binary_sha256,
        "qdisc_sha256": config.expected_qdisc_sha256,
        "firewall_full_sha256": config.expected_firewall_full_sha256,
        "firewall_v4_sha256": config.expected_firewall_v4_sha256,
        "firewall_v6_sha256": config.expected_firewall_v6_sha256,
        "firewall_nft_sha256": config.expected_firewall_nft_sha256,
    }
    for key, expected_value in expected.items():
        actual = payload[key]
        if not isinstance(actual, str) or SHA256_RE.fullmatch(actual) is None:
            raise VerificationError("e01_sha256_invalid")
        if actual != expected_value:
            raise VerificationError(f"e01_{key}_mismatch")
    for key in (
        "wg_aneb_lab_present",
        "ifb_aneb_lab_present",
        "aneb_lab_present",
        "udp_51820_present",
    ):
        if payload[key] is not False:
            raise VerificationError("e01_phase0_residue_present")
    return payload


def _read_handoff(path: Path) -> tuple[bytes, str]:
    try:
        payload = path.read_bytes()
        document = StatusDocument.parse(payload)
    except (OSError, StatusError) as error:
        raise VerificationError("status_file_unreadable") from error
    if document.snapshot.state != HANDOFF:
        raise VerificationError("status_not_handoff")
    return payload, _sha256(payload)


def _assert_status_unchanged(path: Path, baseline: bytes, digest: str) -> None:
    try:
        current = path.read_bytes()
    except OSError as error:
        raise VerificationError("status_changed_during_review") from error
    if current != baseline or _sha256(current) != digest:
        raise VerificationError("status_changed_during_review")


def _transition_status(
    config: VerificationConfig,
    run_command: RunCommand,
    *,
    command: str,
    baseline: bytes,
    baseline_sha256: str,
    evidence: str,
) -> None:
    _assert_status_unchanged(config.status_file, baseline, baseline_sha256)
    completed = _run(
        run_command,
        [
            sys.executable,
            str(config.status_updater),
            "--status-file",
            str(config.status_file),
            command,
            "--executor",
            REVIEWER,
            "--expected-status-sha256",
            baseline_sha256,
            "--evidence",
            evidence,
        ],
        timeout=config.command_timeout_seconds,
        failure_code=f"status_{command.replace('-', '_')}_failed",
    )
    if completed.stderr.strip():
        raise VerificationError(f"status_{command.replace('-', '_')}_failed")
    try:
        state = StatusDocument.parse(config.status_file.read_bytes()).snapshot.state
    except (OSError, StatusError) as error:
        raise VerificationError("status_transition_result_invalid") from error
    expected_state = IDLE if command == "review-release" else LOCKED
    if state != expected_state:
        raise VerificationError("status_transition_result_invalid")


def _interval_label(config: VerificationConfig) -> str:
    interval_value = float(config.interval_seconds)
    return (
        str(int(interval_value))
        if interval_value.is_integer()
        else format(interval_value, "g")
    )


def _success_evidence(config: VerificationConfig) -> str:
    interval = _interval_label(config)
    return (
        f"T+0/T+{interval} 自动独立复核通过：精确设备，5包 PID/ServiceRecord=0，"
        "ANEB 无障碍未启用/未绑定，tun0/VPN=0，Launcher 前台，stayon=0，"
        "Wi-Fi CONNECTED+VALIDATED；"
        f"E-01 {config.expected_version}/active，binary/qdisc/firewall "
        "full/v4/v6/nft 双轮精确且稳定，Phase0 残留=0。"
    )


def _failure_evidence(code: str, config: VerificationConfig) -> str:
    safe_code = re.sub(r"[^a-z0-9_]+", "_", code.casefold())[:96]
    interval = _interval_label(config)
    return (
        f"自动独立复核失败并锁定：T+0/T+{interval} 只读探针未全部通过；"
        f"code={safe_code}。"
    )


def verify_and_transition(
    config: VerificationConfig,
    *,
    run_command: RunCommand = subprocess.run,
    sleep: Sleep = time.sleep,
) -> VerificationOutcome:
    config = _validate_config(config)
    baseline, baseline_sha256 = _read_handoff(config.status_file)
    first_server: Mapping[str, object] | None = None
    try:
        _probe_p40(config, run_command)
        first_server = _probe_server(config, run_command)
        _assert_status_unchanged(config.status_file, baseline, baseline_sha256)
        sleep(config.interval_seconds)
        _assert_status_unchanged(config.status_file, baseline, baseline_sha256)
        _probe_p40(config, run_command)
        second_server = _probe_server(config, run_command)
        _assert_status_unchanged(config.status_file, baseline, baseline_sha256)
        if any(first_server[key] != second_server[key] for key in SERVER_HASH_KEYS):
            raise VerificationError("e01_fingerprints_unstable")
    except VerificationError as error:
        if error.code == "status_changed_during_review":
            return VerificationOutcome(False, error.code, "none", baseline_sha256)
        try:
            _transition_status(
                config,
                run_command,
                command="review-lock",
                baseline=baseline,
                baseline_sha256=baseline_sha256,
                evidence=_failure_evidence(error.code, config),
            )
        except VerificationError as transition_error:
            return VerificationOutcome(
                False,
                transition_error.code,
                "none",
                baseline_sha256,
            )
        return VerificationOutcome(False, error.code, "locked", baseline_sha256)

    try:
        _transition_status(
            config,
            run_command,
            command="review-release",
            baseline=baseline,
            baseline_sha256=baseline_sha256,
            evidence=_success_evidence(config),
        )
    except VerificationError as release_error:
        # A concurrent writer owns the new state; never try to overwrite it.
        try:
            _assert_status_unchanged(config.status_file, baseline, baseline_sha256)
        except VerificationError:
            return VerificationOutcome(
                False,
                "status_changed_during_review",
                "none",
                baseline_sha256,
            )
        # The probes passed but the atomic release itself failed.  Lock the
        # still-original handoff rather than leaving an ambiguous success.
        try:
            _transition_status(
                config,
                run_command,
                command="review-lock",
                baseline=baseline,
                baseline_sha256=baseline_sha256,
                evidence=_failure_evidence(release_error.code, config),
            )
        except VerificationError as lock_error:
            return VerificationOutcome(
                False,
                lock_error.code,
                "none",
                baseline_sha256,
            )
        return VerificationOutcome(
            False,
            release_error.code,
            "locked",
            baseline_sha256,
        )
    return VerificationOutcome(True, "verified", "released", baseline_sha256)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="按配置间隔双轮只读复核 P40/E-01，并以原状态 SHA 原子释放或锁定。",
        allow_abbrev=False,
    )
    parser.add_argument("--status-file", type=Path, default=default_status_file())
    parser.add_argument(
        "--status-updater",
        type=Path,
        default=Path(__file__).resolve().with_name("update_shared_test_status.py"),
    )
    parser.add_argument("--adb-path", default="adb")
    parser.add_argument("--adb-serial", "--serial", dest="adb_serial", required=True)
    parser.add_argument("--ssh-path", default="ssh")
    parser.add_argument("--ssh-host", required=True)
    parser.add_argument("--ssh-key", type=Path, required=True)
    parser.add_argument("--ssh-port", type=int, default=22)
    parser.add_argument("--interval-seconds", type=float, default=10.0)
    parser.add_argument("--command-timeout-seconds", type=float, default=30.0)
    parser.add_argument("--expected-version", required=True)
    parser.add_argument("--expected-binary-sha256", required=True)
    parser.add_argument("--expected-qdisc-sha256", required=True)
    parser.add_argument(
        "--expected-firewall-full-sha256",
        "--expected-firewall-sha256",
        dest="expected_firewall_full_sha256",
        required=True,
    )
    parser.add_argument(
        "--expected-firewall-v4-sha256",
        "--expected-iptables-v4-sha256",
        dest="expected_firewall_v4_sha256",
        required=True,
    )
    parser.add_argument(
        "--expected-firewall-v6-sha256",
        "--expected-iptables-v6-sha256",
        dest="expected_firewall_v6_sha256",
        required=True,
    )
    parser.add_argument(
        "--expected-firewall-nft-sha256",
        "--expected-nft-sha256",
        dest="expected_firewall_nft_sha256",
        required=True,
    )
    return parser


def _config_from_args(args: argparse.Namespace) -> VerificationConfig:
    return VerificationConfig(
        status_file=args.status_file,
        status_updater=args.status_updater,
        adb_path=args.adb_path,
        adb_serial=args.adb_serial,
        ssh_path=args.ssh_path,
        ssh_host=args.ssh_host,
        ssh_key=args.ssh_key,
        ssh_port=args.ssh_port,
        expected_version=args.expected_version,
        expected_binary_sha256=args.expected_binary_sha256,
        expected_qdisc_sha256=args.expected_qdisc_sha256,
        expected_firewall_full_sha256=args.expected_firewall_full_sha256,
        expected_firewall_v4_sha256=args.expected_firewall_v4_sha256,
        expected_firewall_v6_sha256=args.expected_firewall_v6_sha256,
        expected_firewall_nft_sha256=args.expected_firewall_nft_sha256,
        interval_seconds=args.interval_seconds,
        command_timeout_seconds=args.command_timeout_seconds,
    )


def main(
    argv: Sequence[str] | None = None,
    *,
    stdout: TextIO | None = None,
    stderr: TextIO | None = None,
) -> int:
    stdout = stdout or sys.stdout
    stderr = stderr or sys.stderr
    args = build_parser().parse_args(argv)
    try:
        outcome = verify_and_transition(_config_from_args(args))
    except VerificationError as error:
        print(f"ERROR code={error.code}", file=stderr)
        return 2
    if outcome.success:
        print("OK verification=passed transition=handoff->idle", file=stdout)
        return 0
    print(
        f"ERROR code={outcome.code} transition={outcome.transition}",
        file=stderr,
    )
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
