[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$InputDirectory,
    [Parameter(Mandatory = $true)][string]$OutputRoot,
    [Parameter(Mandatory = $true)][ValidatePattern('^[A-Za-z0-9._:-]+$')][string]$CampaignId,
    [Parameter(Mandatory = $true)][ValidateCount(6, 6)][string[]]$PayloadFiles,
    [Parameter(Mandatory = $true)][string]$OfflineReportFile
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'common.ps1')

function Stop-AnEbFinalize {
    param(
        [Parameter(Mandatory = $true)][string]$Code,
        [Parameter(Mandatory = $true)][string]$Message
    )
    throw ($Code + ' ' + $Message)
}

function Get-AnEbCanonicalPayloadNames {
    param([Parameter(Mandatory = $true)][string[]]$Names)
    $canonicalNames = @('meta.json', 'events.jsonl', 'runs.csv', 'summary.csv', 'report.html', 'run.log')
    if (@($Names).Count -ne 6) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'CANONICAL_EVIDENCE_SET requires exactly six payload files'
    }
    $normalized = @()
    foreach ($name in $Names) {
        try {
            Assert-AnEbRelativePath -RelativePath $name
        }
        catch {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'payload path is not safe and relative'
        }
        if ($name -eq 'manifest.json') {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'manifest is generated by the finalizer'
        }
        $isCanonical = $false
        foreach ($canonicalName in $canonicalNames) {
            if ([string]::Equals($name, $canonicalName, [System.StringComparison]::Ordinal)) {
                $isCanonical = $true
                break
            }
        }
        if (-not $isCanonical) {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message ('CANONICAL_EVIDENCE_SET rejects payload name: ' + $name)
        }
        $normalized += $name
    }
    foreach ($name in $normalized) {
        foreach ($other in $normalized) {
            if ($name -cne $other -and [string]::Equals($name, $other, [System.StringComparison]::OrdinalIgnoreCase)) {
                Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'CANONICAL_EVIDENCE_SET contains a case-insensitive duplicate'
            }
        }
    }
    foreach ($canonicalName in $canonicalNames) {
        if (-not ($normalized | Where-Object { [string]::Equals($_, $canonicalName, [System.StringComparison]::Ordinal) })) {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message ('CANONICAL_EVIDENCE_SET is missing: ' + $canonicalName)
        }
    }
    return @($canonicalNames)
}

function Assert-AnEbCanonicalReport {
    param([Parameter(Mandatory = $true)][string]$Text)
    $regexOptions = [System.Text.RegularExpressions.RegexOptions]::Singleline
    $metaMatches = [regex]::Matches($Text, '<meta\s+charset="utf-8"\s*/?>', $regexOptions)
    if ($metaMatches.Count -ne 1) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR requires exactly one UTF-8 meta tag'
    }
    foreach ($forbiddenTag in @('link', 'img', 'iframe', 'object', 'embed', 'base', 'form', 'style', 'svg')) {
        if ([regex]::IsMatch($Text, '(?i)<\s*' + $forbiddenTag + '\b', $regexOptions)) {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR forbids external or active resource tags'
        }
    }
    if ([regex]::IsMatch($Text, '(?i)\s(?:href|src|action|style|on[a-z]+)\s*=', $regexOptions)) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR forbids resource and event attributes'
    }
    $scriptTags = [regex]::Matches($Text, '<script\b', $regexOptions)
    if ($scriptTags.Count -ne 1) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR requires one canonical summary script'
    }
    $scriptPattern = '<script\s+id="canonical-summary"\s+type="application/json">(?<json>.*?)</script\s*>'
    $scriptMatch = [regex]::Match($Text, $scriptPattern, $regexOptions)
    if (-not $scriptMatch.Success) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR canonical summary script attributes are invalid'
    }
    try {
        $null = $scriptMatch.Groups['json'].Value | ConvertFrom-Json
    }
    catch {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR canonical summary is not JSON'
    }

    $sectionIds = @('campaign-verdict', 'disclosure', 'condition-comparison', 'run-table', 'environment', 'evidence-integrity')
    $sectionMatches = [regex]::Matches($Text, '<section\s+id="([^"]+)">', $regexOptions)
    if ($sectionMatches.Count -lt $sectionIds.Count -or $sectionMatches.Count -gt ($sectionIds.Count + 1)) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR section count is not canonical'
    }
    $cursor = 0
    foreach ($sectionId in $sectionIds) {
        $escapedId = [regex]::Escape($sectionId)
        $sectionPattern = '<section\s+id="' + $escapedId + '">\s*<span\s+data-kind="canonical-section">(?<body>.+?)</span>\s*</section\s*>'
        $sectionMatch = [regex]::Match($Text, $sectionPattern, $regexOptions)
        if (-not $sectionMatch.Success -or $sectionMatch.Index -lt $cursor -or [string]::IsNullOrWhiteSpace($sectionMatch.Groups['body'].Value)) {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR required sections are missing or out of order'
        }
        $cursor = $sectionMatch.Index + $sectionMatch.Length
    }
    if ($sectionMatches.Count -eq ($sectionIds.Count + 1)) {
        $failurePattern = '<section\s+id="failure-details">\s*<span\s+data-kind="canonical-section">(?<body>.+?)</span>\s*</section\s*>'
        $failureMatch = [regex]::Match($Text, $failurePattern, $regexOptions)
        if (-not $failureMatch.Success -or $failureMatch.Index -lt $cursor -or [string]::IsNullOrWhiteSpace($failureMatch.Groups['body'].Value)) {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR failure-details section is invalid'
        }
    }
    foreach ($sectionMatch in $sectionMatches) {
        $sectionName = $sectionMatch.Groups[1].Value
        if ($sectionName -notin ($sectionIds + @('failure-details'))) {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'REPORT_GRAMMAR contains an unknown section'
        }
    }
}

function Assert-AnEbPayloadInput {
    param(
        [Parameter(Mandatory = $true)][string]$Directory,
        [Parameter(Mandatory = $true)][string[]]$Names
    )
    Assert-AnEbDirectory -Path $Directory | Out-Null
    $actual = @(Get-AnEbRelativeFiles -Root $Directory | Select-Object -ExpandProperty RelativePath | Sort-Object)
    $expected = @($Names | Sort-Object)
    $diff = @(Compare-Object -ReferenceObject $expected -DifferenceObject $actual)
    if ($diff.Count -ne 0) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'input directory contains an unexpected or missing payload'
    }
    foreach ($name in $Names) {
        Assert-AnEbRegularFile -Path (Join-Path $Directory ($name -replace '/', '\')) | Out-Null
    }
}

function New-AnEbManifestObject {
    param(
        [Parameter(Mandatory = $true)][string]$Directory,
        [Parameter(Mandatory = $true)][string]$ExpectedCampaignId,
        [Parameter(Mandatory = $true)][string[]]$Names
    )
    $mediaTypes = @{
        'meta.json' = 'application/json'
        'events.jsonl' = 'application/x-ndjson'
        'runs.csv' = 'text/csv'
        'summary.csv' = 'text/csv'
        'report.html' = 'text/html'
        'run.log' = 'text/plain'
    }
    $artifacts = @()
    foreach ($name in ($Names | Sort-Object)) {
        $path = Join-Path $Directory ($name -replace '/', '\')
        $item = Assert-AnEbRegularFile -Path $path
        $artifacts += [ordered]@{
            path = $name
            media_type = $mediaTypes[$name]
            size_bytes = [int64]$item.Length
            sha256 = Get-AnEbSha256File -Path $path
        }
    }
    return [ordered]@{
        manifest_version = 'aneb-prototype-manifest-0.1'
        campaign_id = $ExpectedCampaignId
        publication_status = 'NON_RC_ASSEMBLED_UNVERIFIED'
        created_at_utc = Get-AnEbUtcNow
        artifacts = $artifacts
    }
}

try {
    $inputFull = Get-AnEbFullPath -Path $InputDirectory
    $outputFull = Get-AnEbFullPath -Path $OutputRoot
    Assert-AnEbTreeNoReparse -Root $inputFull
    if (Test-Path -LiteralPath $outputFull) {
        Assert-AnEbTreeNoReparse -Root $outputFull
    }
    $payloadNames = Get-AnEbCanonicalPayloadNames -Names $PayloadFiles
    $reportName = [string]$OfflineReportFile
    if ($payloadNames -notcontains $reportName) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'offline report must be one of the payload files'
    }
    Assert-AnEbPayloadInput -Directory $inputFull -Names $payloadNames
    $reportText = Read-AnEbUtf8Strict -Path (Join-Path $inputFull ($reportName -replace '/', '\'))
    Assert-AnEbCanonicalReport -Text $reportText

    if (-not (Test-Path -LiteralPath $outputFull)) {
        Assert-AnEbExistingParents -Path $outputFull
        New-Item -ItemType Directory -Path $outputFull -ErrorAction Stop | Out-Null
    }
    Assert-AnEbDirectory -Path $outputFull | Out-Null
    $finalPath = Join-Path $outputFull $CampaignId
    $partialPath = Join-Path $outputFull ($CampaignId + '.partial')
    if (Test-Path -LiteralPath $finalPath) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'published campaign already exists; use a new campaign id'
    }
    if (Test-Path -LiteralPath $partialPath) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'partial campaign already exists; inspect it before retry'
    }
    New-Item -ItemType Directory -Path $partialPath -ErrorAction Stop | Out-Null
    try {
        Assert-AnEbDirectory -Path $partialPath | Out-Null
        Assert-AnEbPathUnderRoot -Root $outputFull -Path $partialPath | Out-Null
        foreach ($name in $payloadNames) {
            $sourcePath = Join-Path $inputFull ($name -replace '/', '\')
            $destinationPath = Join-Path $partialPath ($name -replace '/', '\')
            $destinationParent = Split-Path -Parent $destinationPath
            if (-not (Test-Path -LiteralPath $destinationParent)) {
                New-Item -ItemType Directory -Path $destinationParent -ErrorAction Stop | Out-Null
            }
            Assert-AnEbDirectory -Path $destinationParent | Out-Null
            Write-AnEbCreateNewBytes -Path $destinationPath -Bytes (Read-AnEbBytes -Path $sourcePath)
        }
        $manifest = New-AnEbManifestObject -Directory $partialPath -ExpectedCampaignId $CampaignId -Names $payloadNames
        Write-AnEbCanonicalJsonCreateNew -Path (Join-Path $partialPath 'manifest.json') -Value $manifest
        $manifestRead = Read-AnEbUtf8Strict -Path (Join-Path $partialPath 'manifest.json') | ConvertFrom-Json
        if ($manifestRead.publication_status -cne 'NON_RC_ASSEMBLED_UNVERIFIED' -or
            $manifestRead.campaign_id -cne $CampaignId -or
            @($manifestRead.artifacts).Count -ne 6) {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'manifest strict readback failed'
        }
        foreach ($artifact in @($manifestRead.artifacts)) {
            Assert-AnEbRelativePath -RelativePath ([string]$artifact.path)
            $artifactPath = Join-Path $partialPath ([string]$artifact.path -replace '/', '\')
            $item = Assert-AnEbRegularFile -Path $artifactPath
            if ([int64]$artifact.size_bytes -ne [int64]$item.Length -or
                [string]$artifact.sha256 -cne (Get-AnEbSha256File -Path $artifactPath)) {
                Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'manifest artifact hash or size mismatch'
            }
        }
        [System.IO.Directory]::Move($partialPath, $finalPath)
    }
    catch {
        Write-Output ("FAIL " + $_.Exception.Message)
        Write-Output ("PARTIAL_PRESERVED " + $partialPath)
        throw
    }
    Write-Output ("PASS NON_RC_ASSEMBLED_UNVERIFIED campaign=" + $CampaignId + " path=" + $finalPath + " files=7")
    exit 0
}
catch {
    if ($_.Exception.Message -notmatch '^FAIL ') {
        Write-Output ("FAIL " + $_.Exception.Message)
    }
    exit 1
}
