[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$InputDirectory,
    [Parameter(Mandatory = $true)][string]$OutputRoot,
    [Parameter(Mandatory = $true)][ValidatePattern('^[A-Za-z0-9._:-]+$')][string]$CampaignId,
    [Parameter(Mandatory = $true)][ValidateCount(6, 6)][string[]]$PayloadFiles,
    [Parameter(Mandatory = $true)][string]$OfflineReportFile
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'common.ps1')

function Stop-AnEbFinalize {
    param(
        [Parameter(Mandatory = $true)][string]$Code,
        [Parameter(Mandatory = $true)][string]$Message
    )
    throw ($Code + ' ' + $Message)
}

function Get-AnEbCanonicalPayloadNames {
    param([Parameter(Mandatory = $true)][string[]]$Names)
    if (@($Names).Count -ne 6) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'exactly six payload files are required'
    }
    $normalized = @()
    foreach ($name in $Names) {
        try {
            Assert-AnEbRelativePath -RelativePath $name
        }
        catch {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'payload path is not safe and relative'
        }
        if ($name -eq 'manifest.json') {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'manifest is generated by the finalizer'
        }
        $normalized += $name
    }
    if (@($normalized | Sort-Object -Unique).Count -ne 6) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'payload paths are duplicated'
    }
    return @($normalized | Sort-Object)
}

function Assert-AnEbPayloadInput {
    param(
        [Parameter(Mandatory = $true)][string]$Directory,
        [Parameter(Mandatory = $true)][string[]]$Names
    )
    Assert-AnEbDirectory -Path $Directory | Out-Null
    $actual = @(Get-AnEbRelativeFiles -Root $Directory | Select-Object -ExpandProperty RelativePath | Sort-Object)
    $expected = @($Names | Sort-Object)
    $diff = @(Compare-Object -ReferenceObject $expected -DifferenceObject $actual)
    if ($diff.Count -ne 0) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'input directory contains an unexpected or missing payload'
    }
    foreach ($name in $Names) {
        Assert-AnEbRegularFile -Path (Join-Path $Directory ($name -replace '/', '\')) | Out-Null
    }
}

function New-AnEbManifestObject {
    param(
        [Parameter(Mandatory = $true)][string]$Directory,
        [Parameter(Mandatory = $true)][string]$ExpectedCampaignId,
        [Parameter(Mandatory = $true)][string[]]$Names
    )
    $artifacts = @()
    foreach ($name in ($Names | Sort-Object)) {
        $path = Join-Path $Directory ($name -replace '/', '\')
        $item = Assert-AnEbRegularFile -Path $path
        $artifacts += [ordered]@{
            path = $name
            size_bytes = [int64]$item.Length
            sha256 = Get-AnEbSha256File -Path $path
        }
    }
    return [ordered]@{
        manifest_version = 'aneb-skeleton-manifest-v0'
        campaign_id = $ExpectedCampaignId
        publication_status = 'verified'
        artifacts = $artifacts
    }
}

try {
    $inputFull = Get-AnEbFullPath -Path $InputDirectory
    $outputFull = Get-AnEbFullPath -Path $OutputRoot
    $payloadNames = Get-AnEbCanonicalPayloadNames -Names $PayloadFiles
    $reportName = [string]$OfflineReportFile
    if ($payloadNames -notcontains $reportName) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'offline report must be one of the payload files'
    }
    Assert-AnEbPayloadInput -Directory $inputFull -Names $payloadNames
    $reportText = Read-AnEbUtf8Strict -Path (Join-Path $inputFull ($reportName -replace '/', '\'))
    if ($reportText -match '(?i)<script|src\s*=|href\s*=\s*["'']https?://|https?://') {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'offline report contains a remote dependency'
    }

    if (-not (Test-Path -LiteralPath $outputFull)) {
        Assert-AnEbExistingParents -Path $outputFull
        New-Item -ItemType Directory -Path $outputFull -ErrorAction Stop | Out-Null
    }
    Assert-AnEbDirectory -Path $outputFull | Out-Null
    $finalPath = Join-Path $outputFull $CampaignId
    $partialPath = Join-Path $outputFull ($CampaignId + '.partial')
    if (Test-Path -LiteralPath $finalPath) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'published campaign already exists; use a new campaign id'
    }
    if (Test-Path -LiteralPath $partialPath) {
        Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'partial campaign already exists; inspect it before retry'
    }
    New-Item -ItemType Directory -Path $partialPath -ErrorAction Stop | Out-Null
    try {
        Assert-AnEbDirectory -Path $partialPath | Out-Null
        foreach ($name in $payloadNames) {
            $sourcePath = Join-Path $inputFull ($name -replace '/', '\')
            $destinationPath = Join-Path $partialPath ($name -replace '/', '\')
            $destinationParent = Split-Path -Parent $destinationPath
            if (-not (Test-Path -LiteralPath $destinationParent)) {
                New-Item -ItemType Directory -Path $destinationParent -ErrorAction Stop | Out-Null
            }
            Assert-AnEbDirectory -Path $destinationParent | Out-Null
            Write-AnEbCreateNewBytes -Path $destinationPath -Bytes (Read-AnEbBytes -Path $sourcePath)
        }
        $manifest = New-AnEbManifestObject -Directory $partialPath -ExpectedCampaignId $CampaignId -Names $payloadNames
        Write-AnEbCanonicalJsonCreateNew -Path (Join-Path $partialPath 'manifest.json') -Value $manifest
        $manifestRead = Read-AnEbUtf8Strict -Path (Join-Path $partialPath 'manifest.json') | ConvertFrom-Json
        if ($manifestRead.publication_status -cne 'verified' -or
            $manifestRead.campaign_id -cne $CampaignId -or
            @($manifestRead.artifacts).Count -ne 6) {
            Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'manifest strict readback failed'
        }
        foreach ($artifact in @($manifestRead.artifacts)) {
            Assert-AnEbRelativePath -RelativePath ([string]$artifact.path)
            $artifactPath = Join-Path $partialPath ([string]$artifact.path -replace '/', '\')
            $item = Assert-AnEbRegularFile -Path $artifactPath
            if ([int64]$artifact.size_bytes -ne [int64]$item.Length -or
                [string]$artifact.sha256 -cne (Get-AnEbSha256File -Path $artifactPath)) {
                Stop-AnEbFinalize -Code 'P012_FINALIZE_FAILED' -Message 'manifest artifact hash or size mismatch'
            }
        }
        [System.IO.Directory]::Move($partialPath, $finalPath)
    }
    catch {
        Write-Output ("FAIL " + $_.Exception.Message)
        Write-Output ("PARTIAL_PRESERVED " + $partialPath)
        throw
    }
    Write-Output ("PASS PUBLISHED campaign=" + $CampaignId + " path=" + $finalPath + " files=7")
    exit 0
}
catch {
    if ($_.Exception.Message -notmatch '^FAIL ') {
        Write-Output ("FAIL " + $_.Exception.Message)
    }
    exit 1
}
